spring.application.name=quanlidatsanthethao
spring.datasource.url=jdbc:mysql://localhost:3307/quanlydatsanthethao?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#cấu hình cho jwt
app.jwt.secret=lnkveokgnrgnrognerjnbfjnbkjbnerkbrekjgnrejgknrelndslnevlgknergeongernoreobgkjgdvivibeigbewifbewogrgoreghnffdjvndjlgehrogh24213325543
# 1 phút
app.jwt.expiration= 60000 
# refresh token: 7 ngày
app.jwt.refreshExpirationMs=180000  